Feature/6 oauth2 google 구현
Your-Lie-in-April/server pull request #10
Opened 2024-02-23 17:56 UTC by squidjiny

## #️⃣연관된 이슈

#6 

## 📝작업 내용

> 
OAuth2를 사용해서 구글에서 개인의 정보를 받아오는 작업

RefreshToken과 AccessToken 구현

Redis(RefreshToken 저장용) 연결 구현

되도록이면 OAuth2UserService로 구현을 하고 싶었지만 조언을 구해 본 결과 저걸 통해서 구현하면 프론트와 연결할 때 꽤 애먹을수도 있고, 만약 프론트에 부담이 가지 않게 하기위해 서버측에 부담이 되는 방향으로 구현을 하게 되면 혼자서는 하기 힘들것이라는 조언을 받았습니다. 또한 Rest하게 구현하기 힘들다는 답변을 받아서 OAuth2UserService는 개인적으로 좀 더 연구를 한 후 적용해야 할 것 같습니다.

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

> RefreshToken 구현을 처음 해봅니다. 의문이 생기는 부분은 꼭 질문해주세요. 당신이 맞을수도 있습니다!
> yml파일은 추후 notion에 올릴 예정입니다.
> 예외처리가 아직 완벽하게 되어있지 않습니다. 내일 맑은 정신으로 다시 들여다보고자 합니다. 보이시는 부분이 있으면 코멘트 달아주세요!

2024-02-24 10:55 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/TimepieceApplication.java
> +@EnableCaching
이 어노테이션은 어디에 사용되나요??

2024-02-24 11:06 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
이 부분은 새로 알게됐는데, 좋네요 고생하셨습니다!
https://dev.gmarket.com/83

2024-02-24 11:08 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(new CommonResponseDto(0, ex.getMessage(), null));
해당 클래스의 두 핸들러 메서드의 반환값은, 아직 미정이어서 이렇게 하신걸까요??

2024-02-24 11:09 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/MemberAccessDeniedException.java
> +public class MemberAccessDeniedException implements AccessDeniedHandler {
이 클래스는 필터에서 접근 거부 시, 실행되는 핸들러 클래스인 것 같은데
클래스 이름을 Exception으로 작성하신 이유가 있으실까요??

2024-02-24 11:10 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/MemberAccessDeniedException.java
> +        CommonResponseDto commonResponseDto = new CommonResponseDto(0, "접근 권한이 없습니다.", null);
에러코드와 메세지는 ENUM으로 한 곳에서 관리해도 좋을 것 같아요!

2024-02-24 11:11 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/MemberEntryPointException.java
> +public class MemberEntryPointException implements AuthenticationEntryPoint {
이 부분도 클래스 이름을 Excpetion으로 작성하신 이유가 있으신가요??

2024-02-24 11:11 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/TokenCreateException.java
> +public class TokenCreateException extends RuntimeException{
예외 이름이 좀 더 설명적이면 좋을 것 같아요!

2024-02-24 11:12 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/redis/RedisConfig.java
> +    private String password = "root";
application-redis.yaml 파일로 따로 작성해주세요!

2024-02-24 11:13 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/redis/RefreshTokenRepository.java
> +import java.util.Optional;
쓰이지않는 부분이 들어가있는 것 같아요

2024-02-24 11:16 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/redis/RefreshTokenRepository.java
> +    RefreshToken findByMemberId(Long memberID);
find~ 로 시작되는 메서드의 반환값을 Optional로 바꾸면 좀 더 일반적인 컨벤션에 맞출 수 있을 것 같아요
관련해서 링크 첨부할게요!
https://tuhrig.de/find-vs-get/

2024-02-24 11:18 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    public static CustomUserDetails create(Member member) {
이 부분 메서드명은 create 보다는 of로 수정하는건 어떨까요??
정적 팩토리 메서드 네이밍 컨벤션을 찾아보면 도움이 될거에요

2024-02-24 11:20 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    private Collection<? extends GrantedAuthority> authorities;
이 부분은 추후에 Set, List  등 권한을 바꿔도 깨지지 않도로 하기위해 Collection으로 작성하신 걸까요??

2024-02-24 11:23 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    public CustomUserDetails(Long id, String email, Collection<? extends GrantedAuthority> authorities) {
이 생성자는 외부에서 직접 호출되는 일이 없고, 정적 팩터리 메서드를 제공하기 위해서라면 private으로 바꿔도 될 것 같네요!

2024-02-24 11:23 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    public static CustomUserDetails create(Member member, Map<String, Object> attributes) {
이 메서드 명은 정적 팩터리 메서드 컨벤션에 따라 of로 수정해도 좋을 것 같아요

2024-02-24 11:25 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    public CustomUserDetails(Long id, String email, Collection<? extends GrantedAuthority> authorities) {
Map 타입인 attributes는 따로 초기화하고 있지 않은데,
null로 초기화되게 놔둘건지 아니면 emptyMap이나 Map::new를 사용할지 고민해봐야겠네요

2024-02-24 11:28 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    private String password;
password는 어디에서도 초기화되지 않는데, getPassword 메서드를 오버라이딩 하기 때문에 넣으신걸까요??

2024-02-24 11:28 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    public void setAttributes(Map<String, Object> attributes) {
이 메서드도 위 정적 팩터리에서만 사용된다면 private으로 닫는게 좋을 것 같아요!

2024-02-24 11:29 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetailsService.java
> +
공백 발견 ㅎ

2024-02-24 11:29 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetailsService.java
> +                .orElseThrow(() -> new RuntimeException("존재하지 않는 사람이라우"));
^~^

2024-02-24 11:35 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtAuthFilter.java
> +            new TokenExpiredException("[doFilterInternal] 토큰의 기한이 만료되었습니다.");
예외를 던지지 않고 만들고만 있어요!

2024-02-24 11:38 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +        this.secretKey = Keys.secretKeyFor(SignatureAlgorithm.HS256);
이 부분은 키를 자동생성해서 매번 달라질 것 같은데, secret과 secretKey를 따로 분리해서 secret을 외부 종속성으로 입력받고 이를 기반으로 키를 생성하는게 좋을 것 같아요!

2024-02-24 11:39 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +    @Transactional
해당 메서드는 쓰이지 않는 것 같아요!
+ @Transactional의 용도는 뭘까요?

2024-02-24 11:40 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +                .setExpiration(new Date(now.getTime() + 1000L * 60 * 1))//유효시간
유효시간도 하드코딩하지말고 application-oauth.yaml에 작성해서 입력받는게 좋을 것 같아요!

2024-02-24 11:41 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +                .setExpiration(new Date(now.getTime() + 1000L * 60 * 3))
이것도요!

2024-02-24 11:42 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +    public String getMemberEmail(String token) {
이 부분도 private으로 바꾸면 좋을 것 같아요!

2024-02-24 11:44 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +        Long info = Long.valueOf(Jwts.parser().setSigningKey(secretKey).parseClaimsJws(token).getBody().get("memberId").toString());
마찬가지로 memberId 정도로 바꾸는게 가독성이 좋을 것 같아요

2024-02-24 11:44 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +        return request.getHeader("Access");
현재 Authorization 헤더가 아닌 커스텀 헤더에 들어가는 건가요??

2024-02-24 11:45 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +        return request.getHeader("Refresh");
이 부분도요!

2024-02-24 11:46 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +        }
try-catch말고 파싱이 실패하면 예외를 던지는건 어떨까요?

2024-02-24 11:47 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/SecurityConfig.java
> +                        .requestMatchers("/v1/oauth2/test").hasRole("USER")
path들을 배열이나 일급객체 같은 걸로 빼서 관리하면 더 깔끔할 것 같아요!

2024-02-24 11:48 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/SecurityConfig.java
> +                        .authenticationEntryPoint(new MemberEntryPointException())
Handler 클래스들을 Component 어노테이션으로 명시해뒀는데, 이를 빈으로 사용하지 않고 있는 것 같아요!
궁금한건 매번 new를 호출하면 새로 인스턴스를 생성하게 되진않을까요??

2024-02-24 11:50 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/controller/OAuth2Controller.java
> +    OAuth2Service oAuth2Service;
private final과 RequiredArgsConstructor를 붙이면 밑에 생성자도 숨길 수 있을 것 같아요

2024-02-24 11:51 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/controller/OAuth2Controller.java
> +@RequestMapping("/v1/oauth2")
저도 이 부분은 조금 고민인데, 클래스 위 RequestMapping에 버전(v1)을 표시하면 추후 업데이트가 발생했을 때 버저닝을 위해 새로운 컨트롤러를 만들거나 전부 수정하게 될 수 있을 것 같아요!

2024-02-24 11:53 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/controller/OAuth2Controller.java
> +    public ResponseEntity<?> getGoogleAuthUrl(HttpServletRequest request) throws Exception {
"?" 와일드카드 대신 Void를 써도되지 않을까요?

2024-02-24 11:58 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/controller/OAuth2Controller.java
> +    public ResponseEntity<CommonResponseDto> sign(HttpServletRequest request,
![image](https://github.com/Your-Lie-in-April/server/assets/121238128/84610ea7-0f71-4a70-b86f-2e55202e94e9)

위와 같이 작성하면 Raw 타입 사용과 비검사 형변환으로 인한 경고를 피할 수 있어요! (아래 대부분의 메서드에서도요!)

2024-02-24 12:04 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/controller/OAuth2Controller.java
> +    @GetMapping(value = "/reissue")
PostMapping을 쓰는게 좀 더 자연스러운 것 같아요!

2024-02-24 12:06 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/domain/Member.java
> +    private String provider;
provider 필드를 둔 건 확장성 때문일까요??

2024-02-24 12:07 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/domain/Member.java
> +    @ElementCollection(fetch = FetchType.EAGER)
확장성을 위해 role 테이블을 따로 만드는걸까요??

2024-02-24 12:08 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/domain/Member.java
> +    public Member(String provider, String nickname, String email, String state, String profileImageUrl, List<String> role){
사용되지 않는 것 같아요!

2024-02-24 12:10 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/dto/CommonResponseDto.java
> +    private final T data;
해당 클래스에서만 필드에 final을 붙이신 이유가 있을까요??

2024-02-24 12:11 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/repository/MemberRepository.java
> +    Member findMemberById(Long Id);
마찬가지로 Optional을 반환하는게 좋을 것 같아요!

2024-02-24 12:12 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +    private String googleRedirectUrl = "http://localhost:8080/v1/oauth2/login/google";
전부 외부로 빼는게 좋을 것 같네요

2024-02-24 12:23 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        String resultJson = restTemplate.getForObject(requestUrl, String.class);
+ 여기선 getForEntity 대신 getForObject를 사용하신 이유가 있나요??

2024-02-24 12:24 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        role.add("ROLE_USER");
role을 새로 만드는 로직은 아래 if 조건이 true인 경우에만 필요한 것 같아요!

2024-02-24 12:27 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +                    .provider("Google")
이것도 하드코딩하지 않고 사용하는 방법은 없을까요??

2024-02-24 12:28 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +                    .profileImageUrl(String.valueOf(oAuthMemberResponse.getPicture()))
String.valueOf로 감싸는 이유가 있을까요?

2024-02-24 12:28 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +                    .email(String.valueOf(oAuthMemberResponse.getEmail()))
22

2024-02-24 12:29 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +            tokens.put("Refresh", refreshToken);
123-132, 137-146의 내용은 겹쳐서 if-else문 밖으로 빼는게 좋을 것 같아요

2024-02-24 12:33 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        final RefreshToken refreshToken = refreshTokenRepository.findByMemberId(memberId);
여기만 final인 이유가 있을까요?

2024-02-24 12:33 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
감사합니다!

2024-02-24 12:35 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(new CommonResponseDto(0, ex.getMessage(), null));
사실 커스텀핸들러를 잘못 설계하면 너무 많아지는 경험을 해봐서 섣부르게 만들기 곤란하더군요 @-@ 그래서 좀 더 고민해보고자 제일 필요하다고 느껴지는것(이름)을 먼저 설계해서 그런 것 같습니다. 내용을 고민중이에요.

2024-02-24 12:35 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        Member member = memberRepository.findMemberById(memberId);
findMemberById()가 Optional을 반환하지 않아서, 리스크가 서비스 코드까지 전이가 되는 것 같아요

2024-02-24 12:36 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/MemberAccessDeniedException.java
> +public class MemberAccessDeniedException implements AccessDeniedHandler {
일단 핸들러를 만들면 뒤에 -Exception으로 끝나야한다는 강박이 있어서 이렇게 했습니다. 빼는게 맞다고 생각하십니까?

2024-02-24 12:36 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/MemberAccessDeniedException.java
> +        CommonResponseDto commonResponseDto = new CommonResponseDto(0, "접근 권한이 없습니다.", null);
고려해볼만한 의견 같습니다!

2024-02-24 12:36 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +            refreshTokenRepository.save(new RefreshToken(memberId, newRefreshToken));
새 refreshToken을 저장하는데, 기존 refreshToken을 삭제하는 로직은 빠진 것 같아요!

2024-02-24 12:36 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/MemberEntryPointException.java
> +public class MemberEntryPointException implements AuthenticationEntryPoint {
위와 동일합니다

2024-02-24 12:37 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/TokenCreateException.java
> +public class TokenCreateException extends RuntimeException{
좋은 의견입니다! 작명을 좀 더 생각해보도록 하겠습니다.

2024-02-24 12:37 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/redis/RedisConfig.java
> +    private String password = "root";
redis yml 파일 작성을 할 때 deprecated 되었다고 뜨던데 data 하위 redis로 작성하는게 맞을까요?

2024-02-24 12:39 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +            new TokenCreateException("accessToken 제작 실패");
예외를 생성만하고 던지질않네요!

2024-02-24 12:40 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        return tokens;
else를 들어내고 if 안에서 빠른 return을 해도 좋을 것 같아요

2024-02-24 12:41 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        if(refreshToken.getRefreshToken().equals(jwtProvider.resolveRefreshToken(request))){
이 부분은 refreshToken을 서버에서 임의로 삭제 등, 운영/관리를 위해 작성하신 걸까요?

2024-02-24 12:42 UTC, jang-namu reviewed
정말 고생하셨습니다!
코드 확인해서 몇 가지 리뷰 달아두었으니 확인부탁드려요~!

2024-02-24 13:05 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +            refreshTokenRepository.save(new RefreshToken(memberId, newRefreshToken));
생각만 하고 구현을 안했네요

AccessToken 재발급 쪽에서 구현할거같습니다

2024-02-24 13:05 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +            new TokenCreateException("accessToken 제작 실패");
어쩐지 안되더라.

2024-02-24 13:05 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        return tokens;
고려해보겠습니다!

2024-02-24 13:06 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        if(refreshToken.getRefreshToken().equals(jwtProvider.resolveRefreshToken(request))){
말씀이 정확하게 이해가 안되는데 자세히 설명해주세요

2024-02-24 13:15 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/redis/RefreshTokenRepository.java
> +    RefreshToken findByMemberId(Long memberID);
감사합니다!

2024-02-24 13:15 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    public static CustomUserDetails create(Member member) {
네이밍 센스가 모자랍니다ㅠㅠㅠㅠㅠ 참고해보겠습니다!

2024-02-25 15:59 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/redis/RefreshTokenRepository.java
> +import java.util.Optional;
원래 refreshToken 존재 여부를 Optional로 했었는데 RefreshToken이 동일한지 검사하는 과정에서 Optional 말고 RefreshToken으로 불러와야 깔 수 있더라고요... 그래서 안 쓰게 되었습니다. 지우겟습니다!

2024-02-25 16:00 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    private Collection<? extends GrantedAuthority> authorities;
사실 처음 구현해보는거다보니 기한 안에 구현을 못할까봐 최대한 예외, 오류가 안나는 방향으로 코딩해서 그런 것 같습니다. List를 사용하니까 그쪽으로 고치도록 하겠습니다.

2024-02-25 16:00 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    public CustomUserDetails(Long id, String email, Collection<? extends GrantedAuthority> authorities) {
고려해보겠습니다!

2024-02-25 16:01 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    public static CustomUserDetails create(Member member, Map<String, Object> attributes) {
컨벤션 너무 숙지가 안되네요 허허

계속 적용하려고 노력해서 잘 숙지가 되길 바래봅니다... 허허

2024-02-25 16:02 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    private String password;
맞습니다

2024-02-25 16:02 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetailsService.java
> +
엄.

2024-02-25 16:03 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetailsService.java
> +                .orElseThrow(() -> new RuntimeException("존재하지 않는 사람이라우"));
UserDetails에서 당연히 잘못 만들어서 오류 날 줄 알고 오류나면 고쳐야지~ 했었는데 오류가 안나서 설계 미스를 그냥 지나쳤네요 ㅋㅋㅋㅋ... 찾아주셔서 감사합니다

2024-02-25 16:04 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtAuthFilter.java
> +            new TokenExpiredException("[doFilterInternal] 토큰의 기한이 만료되었습니다.");
...

2024-02-25 16:04 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +        this.secretKey = Keys.secretKeyFor(SignatureAlgorithm.HS256);
yml 업데이트하겠습니다~

2024-02-25 16:05 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +    @Transactional
redis에서 데이터를 찾을 때 트랜잭션을 사용하는것을 보고 달아놨었는데 솔직히 필요없을거같습니다.

2024-02-25 16:05 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +                .setExpiration(new Date(now.getTime() + 1000L * 60 * 1))//유효시간
수정하겠습니다!

2024-02-25 16:05 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +    public String getMemberEmail(String token) {
고려해보겠습니다!

2024-02-25 16:05 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +        String info = Jwts.parser().setSigningKey(secretKey).parseClaimsJws(token).getBody().getSubject();
좋습니다

2024-02-25 16:06 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +        Long info = Long.valueOf(Jwts.parser().setSigningKey(secretKey).parseClaimsJws(token).getBody().get("memberId").toString());
좋습니다

2024-02-25 16:07 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +        return request.getHeader("Refresh");
위 코멘트와 동일합니다.

2024-02-25 16:07 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +        }
좋습니다

2024-02-25 16:46 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +                    .profileImageUrl(String.valueOf(oAuthMemberResponse.getPicture()))
처음에 오류 못찾아서 감싸놨었는데 필요한거 하나 빼먹어서 그런거였습니다.

지워도 문제없습니다

2024-02-26 00:14 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(new CommonResponseDto(0, ex.getMessage(), null));
음,, 아뇨 그런의미는 아니었어요
추후에 에러 코드와 메시지를 enum으로 관리하면 좋을 것 같습니다. 고생하셨어요!

2024-02-26 00:15 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/MemberAccessDeniedException.java
> +public class MemberAccessDeniedException implements AccessDeniedHandler {
음~~ 해당 클래스은 예외를 처리하능 핸들러이기 때문에 예외라는 이름은 오해의 여지가 있을 것 같아요!

2024-02-26 00:27 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/redis/RedisConfig.java
> +    private String password = "root";
찾아보니 스프링부트3으로 넘어오면서 변경됐다고 하네요!
spring.data.redis로 작성하시면 될 것 같아요

관련해서 링크 첨부합니다~
[[spring-project😀](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#redis-properties)](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#redis-properties)

2024-02-26 00:30 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    private String password;
password 필드를 없애고 오버라이딩한 메서드에 null 또는 ""으로 빈 문자열을 반환하도록 하는건 어떨까요?

2024-02-28 17:15 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/controller/OAuth2Controller.java
> +    public ResponseEntity<?> getGoogleAuthUrl(HttpServletRequest request) throws Exception {
void 하면 오류나네요

2024-02-28 17:15 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/controller/OAuth2Controller.java
> +    public ResponseEntity<?> getGoogleAuthUrl(HttpServletRequest request) throws Exception {
아니네요 기분탓이였던걸로

2024-02-28 17:18 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/controller/OAuth2Controller.java
> +    @GetMapping(value = "/reissue")
수정했습니다

2024-02-28 17:18 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/domain/Member.java
> +    private String provider;
다른 서비스 확장도 염두에 두고 만들었습니다

2024-02-28 17:19 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/domain/Member.java
> +    @ElementCollection(fetch = FetchType.EAGER)
원래 role을 따로 만들지 않나요...? 어떻게 저장하시나요...?

2024-02-28 17:26 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/domain/Member.java
> +    public Member(String provider, String nickname, String email, String state, String profileImageUrl, List<String> role){
원래 회원가입을 할 때 사용할 예정이였어서

길게 있던 builder 패턴을 이제 저걸로 대체하지 않을까 싶습니다

2024-02-28 17:28 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/dto/CommonResponseDto.java
> +    private final T data;
무슨 뜻인지 정확하게 이해는 못했으나

저는 중요하다고 생각하는 필드에는 final을 붙이는 편입니다.

그리고 사실은

final 안붙였다고 인텔리제이가 노란줄로 꼽줬습니다.

2024-02-28 18:05 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +    private String googleRedirectUrl = "http://localhost:8080/v1/oauth2/login/google";
이거는 방법을 좀 더 생각해봐야할거같네요

2024-02-28 18:08 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        String resultJson = restTemplate.getForObject(requestUrl, String.class);
webClient로 수정했습니다

2024-02-28 18:08 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        if(!(member.isPresent())) {
수정했습니다.

2024-02-28 18:08 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/repository/MemberRepository.java
> +    Member findMemberById(Long Id);
이거는 제가 좀 더 알아보고 바꾸도록 하겠습니다

2024-02-28 18:09 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        role.add("ROLE_USER");
수정했습니다

2024-02-28 18:10 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +                    .provider("Google")
이것도 조금 더 알아봐야 할 것 같습니다. yml 말고 다른쪽으로 조금 알아보고 있습니다

2024-02-28 18:10 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +                    .email(String.valueOf(oAuthMemberResponse.getEmail()))
22

2024-02-28 18:11 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +            tokens.put("Refresh", refreshToken);
수정했습니다

2024-02-29 04:44 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/domain/Member.java
> +    @ElementCollection(fetch = FetchType.EAGER)
아, 제가 잘못이해했네요. 이 방법이 맞는 것 같습니다!

Role이 Enum이라 해당 어노테이션을 사용하신걸까요?
+ FetchType만 Lazy로 수정부탁드려요!

2024-02-29 04:44 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/dto/CommonResponseDto.java
> +    private final T data;
음,, 그러면 혹시 정아님이 생각하시는 중요하다의 기준은 무엇인지 알수있을까요?

2024-02-29 04:51 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        if(refreshToken.getRefreshToken().equals(jwtProvider.resolveRefreshToken(request))){
요청 헤더에 함께 들어온 리프레쉬 토큰이, 성공적으로 decrypt 되었다면 그 자체로 토큰이 서버에서 발급된 것인지에 대한 검증은 끝났다고 이해할 수 있을 것 같아서요.

그것과는 별개로 서버에서 리프레쉬 토큰을 저장하고, 매번 reissue 요청마다 리프레쉬 토큰이 DB에 저장된 정보와 일치하는지 확인하도록 작성하면, 토큰 탈취 시에 서버에서 부분적으로 대처할 가능성이 생깁니다.

2024-02-29 04:54 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +        return " ";
공백제거 부탁드려요.

2024-02-29 06:02 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/dto/CommonResponseDto.java
> +    private final T data;
사실 위에거보다 아래꺼 이유가 큰데,,,

왜 final을 다는지 찾아보니까 멀티스레드 환경에서도 안전성이 보장된다 이런 이유가 있네요

굳이 달 필요도 없앨 필요도 없는 그런거 같습니다.

2024-02-29 06:03 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        final RefreshToken refreshToken = refreshTokenRepository.findByMemberId(memberId);
불변성이 보장되면 좋을거라고 생각했었는데

의존성 주입 방법 `@RequiredArgment`로 수정하면서 충돌날까봐 뺐습니다

2024-02-29 06:23 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        Member member = memberRepository.findMemberById(memberId);
수정했습니다

2024-02-29 06:26 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/domain/Member.java
> +    @ElementCollection(fetch = FetchType.EAGER)
Role이 List라는것은 Role역할이 추후에 여러개 들어갈수도 있을거같은데 Lazy로 하면 나중에 권한이 있는데도 권한이 없다는 오류가 날 수도 있지 않을까요...?

2024-02-29 06:30 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/service/OAuth2Service.java
> +        if(refreshToken.getRefreshToken().equals(jwtProvider.resolveRefreshToken(request))){
구현 방법을 찾아볼때 사실 저 로직이  있는 코드를 잘 보지 못한것은 맞습니다.

그런데 동일한지 검사를 안 하는게 더 이해가 되지 않아서 동일한지 검사하는 로직도 넣어 놓았습니다.

제가 구현한 토큰 서비스 특성 상 AccessToken을 재발급할때 RefreshToken도 재발급 하기 때문에 탈취되어도 비교적 안전하다라는 장점을 살리기 위해선 저 로직이 들어있는게 맞는 것 같습니다.

2024-02-29 06:31 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/controller/OAuth2Controller.java
> +    OAuth2Service oAuth2Service;
수정했습니다

2024-02-29 06:31 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/SecurityConfig.java
> +                        .authenticationEntryPoint(new MemberEntryPointException())
생각해보지 못했던 문제라 조금 더 생각해보겠습니다.

2024-02-29 13:01 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/domain/Member.java
> +    @ElementCollection(fetch = FetchType.EAGER)
음,, 제 생각에는 문제가 없을 것 같은데 어떤 부분에서 그렇게 생각하셨나요?

2024-02-29 13:14 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/dto/CommonResponseDto.java
> +    private final T data;
말씀하신 멀티스레드 환경에서의 안정성은 이 경우에 꼭 들어맞지는 않는 것 같습니다만,

> 굳이 달 필요도 없앨 필요도 없는 그런거 같습니다.
여기에는 동의할 수 밖에 없네요. 다만, final을 쓰되 일관되게 써야한다고 생각해서 혹시 사용하시는데 기준이 있는지 궁금했습니다!

2024-02-29 13:18 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/CustomUserDetails.java
> +    public static CustomUserDetails of(Member member) {
메서드명으로는 from이 취지에 더 맞는 것 같습니다..

2024-03-03 15:34 UTC, jang-namu requested changes
1. JwtProvieder::saveTokenInfo 삭제
2. Member::role FetchType.LAZY

두 개의 코멘트만 확인부탁드려요~

2024-03-03 15:34 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/JwtProvider.java
> +    @Transactional
이 메서드는 여전히 사용되지 않는 것 같습니다!

2024-03-03 15:34 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/security/SecurityConfig.java
> +                        .authenticationEntryPoint(new MemberEntryPointException())
우선 닫고 다른 이슈로 생성하겠습니다.

2024-03-03 15:34 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/controller/OAuth2Controller.java
> +    public ResponseEntity<CommonResponseDto> sign(HttpServletRequest request,
아직 수정 안됐는데 이것도 이슈로 달겠습니다.

2024-03-03 15:34 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/domain/Member.java
> +    @ElementCollection(fetch = FetchType.EAGER)
의견주세요

2024-03-03 17:17 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/domain/Member.java
> +    @ElementCollection(fetch = FetchType.EAGER)
이 부분을 생각을 쭉 해봤는데

제가 문제가 생길것이라고 예상을 한 것은 Lazy로 role list를 불러오게 되면 String값이 아닌 Role 객체 자체가 불려오게 되기 때문에 오류가 생길것이라고 생각을 했었습니다.

그런데 로직을 다시 생각해보니 검증 과정에서 Role 객체에서 getRole로 안의 String값을 불러오는 행위를 한다는 사실이 뒤늦게 생각났습니다.

제가 봤던 사례들도 Eager를 쓰는 경우는 Role List가 아닌 Role Table을 따로 만든 경우라는것을 알게 되었습니다

그래서 저희 프로젝트의 경우 Lazy를 써도 문제가 생기지 않을 것 같습니다

현재 자취방에 인터넷이 설치되지 않아서 코딩에 많은 어려움이 있네요ㅠㅠ

빠른 시일내에 해결해서 빠른 응답을 하도록 하겠습니다.

기다려주셔서 감사합니다.

2024-03-04 02:36 UTC, jang-namu approved these changes

2024-03-04 02:36 UTC, merged