feat: 유효성검사 추가#119
Your-Lie-in-April/server pull request #120
Opened 2024-07-20 12:53 UTC by squidjiny

## #️⃣연관된 이슈

> ex) #이슈번호, #이슈번호

close #119 

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

- [ ] 프로젝트 시작일 > 프로젝트 마감일 일 경우 400
- [ ] 프로젝트 시작시간 > 프로젝트 마감시간 일 경우 400
- [ ] 시작일, 마감일 NotBlank
- [ ] 시작시간, 마감시간 NotBlank
- [ ] 배경색 Pattern

### 스크린샷 (선택)

만약 유효성검사를 통과하지 못하는것이 여러개라면, 위의 요소부터 차례대로 하나씩만 응답에 포함. (여러개 보내줘도 프론트에선 의미가 없다곤 하는데... 여러개도 가능은 합니다)

![image](https://github.com/user-attachments/assets/c43b187f-2637-4206-8c7c-89d3ced9c35c)

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

![image](https://github.com/user-attachments/assets/055162ae-dcd5-4bc6-b3f3-1aede84f1dc8)

start- 들이랑 end- 들 유효성 검사 추가에 상당히 애로사항이 있어서... 결국 커스텀 어노테이션을 달아서 추가했는데 저럴빠엔 service단에 추가하는게 나을까요?

요일은 추가하다가 굳이 할 필요 없을거 같아서 뺐습니다.

2024-07-23 00:11 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/dto/schedule/ScheduleCreateUpdateRequest.java
> +    @NotEmpty(message = "스케줄은 적어도 하나 이상의 값을 넣어야 저장할 수 있습니다.")
이거 validation이 정상적으로 되나요??

2024-07-23 00:11 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/dto/schedule/ScheduleCreateUpdateRequest.java
> +    @NotEmpty(message = "스케줄은 적어도 하나 이상의 값을 넣어야 저장할 수 있습니다.")
SchedileDayRequest에도 필요할 것 같아요

2024-07-23 12:19 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/dto/schedule/ScheduleCreateUpdateRequest.java
> +    @NotEmpty(message = "스케줄은 적어도 하나 이상의 값을 넣어야 저장할 수 있습니다.")
slack 참고해주세요!

현재 [] 같은 빈 배열은 정상적으로 예외처리가 되고 있지만 [] 안에 {} 하나만 들어가도 예외처리가 되지 않는상황인데 그냥 커스텀 어노테이션으로 자세하게 예외처리 하는게 나을까요?

2024-07-27 08:04 UTC, jang-namu reviewed
고생하셨습니다.!

2024-07-27 08:04 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/dto/schedule/ScheduleCreateUpdateRequest.java
> +    @NotEmpty(message = "스케줄은 적어도 하나 이상의 값을 넣어야 저장할 수 있습니다.")
중첩된 배열, JSON 구조 Validation - 슬랙 참고

2024-07-29 07:48 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/controller/ProjectController.java
> +    public ResponseEntity<CommonResponse<?>> createProject(@RequestBody @Valid ProjectCreateUpdateRequest request,
[fc7e03b](https://github.com/Your-Lie-in-April/server/pull/120/commits/fc7e03bd95ad29e9b0541504aeb58fcf1a134123)

2024-07-29 07:48 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/controller/ScheduleController.java
> +                                                            @RequestBody @Valid ScheduleCreateUpdateRequest request,
[fc7e03b](https://github.com/Your-Lie-in-April/server/pull/120/commits/fc7e03bd95ad29e9b0541504aeb58fcf1a134123)

2024-07-31 14:59 UTC, jang-namu reviewed
고생하셨습니다. 수정해야돌 부분 몇 개 찾았어요.

2024-07-31 14:59 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/dto/schedule/ScheduleDeleteRequest.java
> +    @NotBlank(message = "프로젝트 선택은 필수입니다.")
이것만 왜 NotBlank에요?

2024-07-31 14:59 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/dto/schedule/ScheduleDeleteRequest.java
> +    @NotBlank(message = "프로젝트 선택은 필수입니다.")
![스크린샷 2024-07-31 오후 11 35 55](https://github.com/user-attachments/assets/7ebeb123-34ad-4772-9f2d-dc53bc31f23f)

NotBlank는 문자열 시퀀스 형식에만 사용가능하네요.

2024-07-31 14:59 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/dto/schedule/ScheduleDeleteRequest.java
> +    @NotBlank(message = "프로젝트 선택은 필수입니다.")
그건 그렇고 이거 API 엔드포인트에 이미 projectId가 포함되어 있네요

2024-07-31 14:59 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/dto/member/UpdateNicknameRequest.java
> +    @NotBlank(message = "프로젝트 선택은 필수입니다.")
여기도 NotBlank가 쓰이면 안될것 같네요,

2024-07-31 14:59 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/dto/project/TransferPrivilegeRequest.java
> +    @NotBlank(message = "권한을 넘겨줄 멤버의 아이디를 입력 해 주세요.")
NotBlank -> NotNull

2024-07-31 14:59 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
이거는 MethodArgumentNotValidException 때문에 변경하신 걸까요?
그런거라면 ResponseEntityExceptionHandler를 구현하도록 냅두고, handleMethodArgumentNotValid 메서드를 오버라이딩 하면될 것 같습니다.

```java
@RestControllerAdvice
public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
    @Override
    protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException ex, HttpHeaders headers, HttpStatusCode status, WebRequest request) {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(CommonResponse.error("유효성 검사 실패", ex.getBindingResult().getAllErrors().get(0).getDefaultMessage()));
    }
}
```

2024-07-31 15:09 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
저렇게 하면 된다는걸 알지만

ResponseEntityExceptionHandler 기능을 전혀 안쓰고 있던것도 맞아서 지웠습니다

2024-07-31 15:10 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/dto/schedule/ScheduleDeleteRequest.java
> +    @NotBlank(message = "프로젝트 선택은 필수입니다.")
그건 좀 수정할필요가 있겠는걸

2024-07-31 15:10 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/dto/schedule/ScheduleDeleteRequest.java
> +    @NotBlank(message = "프로젝트 선택은 필수입니다.")
DTO에서 ID 지웁니다 그럼?

2024-07-31 15:26 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
음, 전혀 안쓰고 있지는 않을 것 같은데요

2024-07-31 15:27 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/dto/schedule/ScheduleDeleteRequest.java
> +    @NotBlank(message = "프로젝트 선택은 필수입니다.")
ㅔ

2024-08-07 12:23 UTC, jang-namu requested changes
남은 코멘트 참고

2024-08-07 12:23 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/GlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException ex, HttpHeaders headers, HttpStatusCode status, WebRequest request) {
Object는 좀 구리긴한데, 암튼 오케이

2024-08-07 12:30 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/GlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException ex, HttpHeaders headers, HttpStatusCode status, WebRequest request) {
저거 object밖에 안될건디?

2024-08-07 12:33 UTC, squidjiny commented on timepiece/src/main/java/com/appcenter/timepiece/dto/member/UpdateNicknameRequest.java
> +    @NotBlank(message = "프로젝트 선택은 필수입니다.")
앗. 커밋 하나 빼먹엇네
확인

2024-08-08 05:28 UTC, jang-namu approved these changes
고생하셨습니다.

2024-08-08 05:28 UTC, jang-namu commented on timepiece/src/main/java/com/appcenter/timepiece/common/exception/GlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException ex, HttpHeaders headers, HttpStatusCode status, WebRequest request) {
아,, ㅋㅋㅋㅋㅋ 확인이요.

2024-08-08 08:14 UTC, merged